language: node_js
node_js:
  - "6"
install:
  - npm install
script:
  - npm test
deploy:
  provider: npm
  api_key: $NPM_TOKEN
  email: radu.helstern@gmail.com
  skip_cleanup: true
  on:
    tags: true