language: node_js
node_js:
  - "6"
install:
  - npm install
script:
  - npm test
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
  provider: npm
  api_key: $NPM_TOKEN
  email: radu.helstern@gmail.com
  skip_cleanup: true
  on:
    tags: true